### ISSUE TITLE
include depth of relations

### ISSUE THREAD

**Issue by p3sn** [contentful/contentful-metalsmith#48]
Hi All, 

I have set include to 10, but still I don't get all data. At a depth of 3, I only get the .sys data. 

```
---
title: Test Title
contentful:
  content_type: defaultPage
  include: 10
  entry_filename_pattern: page/${ fields.slug }/index
  entry_template: page.html  
layout: page.html
---
```

Do you have any idea why I don't get all content of all objects?

Regards, Peter
